from collections import OrderedDict
from sqlite3.dbapi2 import Date

from .base import ApiBase
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

class SalesOrders(ApiBase):
    SIMPLE_FIELDS = [
        'canHaveStackable',
        'ccApproved',
        'excludeCommission',
        'getAuth',
        'ignoreAvs',
        'isMultiShipTo',
        'isRecurringPayment',
        'isTaxable',
        'paypalProcess',
        'revRecOnRevCommitment',
        'saveOnAuthDecline',
        'shipComplete',
        'shipIsResidential',
        'syncPartnerTeams',
        'syncSalesTeams',
        'taxDetailsOverride',
        'taxRegOverride',
        'toBeEmailed',
        'toBeFaxed',
        'toBePrinted',
        'tranIsVsoeBundle',
        'vsoeAutoCalc',
        'customFieldList',
        'actualShipDate',
        'ccExpireDate',
        'endDate',
        'nextBill',
        'paymentEventDate',
        'revRecEndDate',
        'revRecStartDate',
        'salesEffectiveDate',
        'shipDate',
        'startDate',
        'taxPointDate',
        'tranDate',
        'validFrom',
        'altHandlingCost',
        'altSalesTotal',
        'altShippingCost',
        'balance',
        'deferredRevenue',
        'discountTotal',
        'estGrossProfit',
        'estGrossProfitPercent',
        'exchangeRate',
        'giftCertApplied',
        'handlingCost',
        'handlingTax1Rate',
        'oneTime',
        'recognizedRevenue',
        'recurAnnually',
        'recurMonthly',
        'recurQuarterly',
        'recurWeekly',
        'requiredDepositAmount',
        'requiredDepositDue',
        'requiredDepositPercentage',
        'shippingCost',
        'shippingTax1Rate',
        'subTotal',
        'tax2Total',
        'taxRate',
        'taxTotal',
        'total',
        'totalCostEstimate'
    ]

    RECORD_REF_FIELDS = [
        'billAddressList',
        'billingSchedule',
        'class',
        'createdFrom',
        'creditCard',
        'creditCardProcessor',
        'currency',
        'customForm',
        'department',
        'discountItem',
        'drAccount',
        'entity',
        'entityTaxRegNum',
        'fxAccount',
        'handlingTaxCode',
        'intercoTransaction',
        'job',
        'leadSource',
        'location',
        'messageSel',
        'nexus',
        'opportunity',
        'partner',
        'paymentMethod',
        'paymentOption',
        'paymentProcessingProfile',
        'promoCode',
        'revRecSchedule',
        'salesGroup',
        'salesRep',
        'shipAddressList',
        'shipMethod',
        'shippingTaxCode',
        'subsidiary',
        'subsidiaryTaxRegNum',
        'taxItem',
        'terms',
    ]

    def __init__(self, ns_client):
        ApiBase.__init__(self, ns_client=ns_client, type_name='SalesOrder')